ContactsApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
path('',views.index,name='index'),
path('get_contact_details',views.get_contact_details,name='get_contact_details'),
path('add_new_number',views.add_new_number,name='add_new_number'),
path('create_new_contact',views.create_new_contact,name='create_new_contact'),
]

innovaTask/urls.py
from django.contrib import admin
from django.urls import path,include

#mapping to the new app url file
urlpatterns = [
    path('ContactsApp/',include('ContactsApp.urls')),
    path('admin/', admin.site.urls),
]

ContactsApp/models.py
from django.db import models
from django.db import models

#simple we do not need to have more than two tables. It is a simple case

#first model is contact
class Contact(models.Model):
    #we don't need to implement id field it is there by default.
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    class Meta:
        db_table = "Contact"

#the second model is phone number which has many-to-one relationship with contact
class PhoneNumber(models.Model):
    #we don't need to implement id field it is there by default.
    country_code = models.CharField(max_length=5)
    #we need the phone number to be unique to avoid duplicates
    phone_number = models.CharField(max_length=15,unique=True)
    contact_id = models.ForeignKey(Contact, on_delete=models.CASCADE)
    class Meta:
        db_table = "PhoneNumber"

ContactsApp/forms.py
from django import forms
from ContactsApp.models import Contact,PhoneNumber


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["first_name", "last_name", "email"]


class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ["country_code", "phone_number", "contact_id"]

ContactsApp/views.py
from django.shortcuts import render
from ContactsApp.models import Contact,PhoneNumber
from ContactsApp.forms import PhoneNumberForm, ContactForm
from django.shortcuts import redirect

#creating the landing page
def index(request):
    contact_list = Contact.objects.all()
    context = {'contact_list': contact_list }
    return render(request, 'ContactsApp/contacts.html', context)


def get_contact_details(request):
    if request.method == 'GET':
        try:
            contact = Contact.objects.get(id=request.GET.get('contact_id'))
            context = {'contact': contact }
            return render(request, 'ContactsApp/contact.html', context)
        except:
            return render(request, 'ContactsApp/error.html')



def add_new_number(request):
    if request.method == 'POST':
        form = PhoneNumberForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('./')
    if request.method == 'GET':
        try:
            numberForm = PhoneNumberForm( initial= {'contact_id': request.GET.get('contact_id')})
            return render(request, 'ContactsApp/create_number.html', {'form': numberForm})
        except Exception as e:
            return render(request, 'ContactsApp/error.html')



def create_new_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('./')
    if request.method == 'GET':
        try:
            contactForm = ContactForm()
            return render(request, 'ContactsApp/create_contact.html', {'form': contactForm})
        except Exception as e:
            return render(request, 'ContactsApp/error.html')

templates/ContactsApp/contact.html
<h1> Contact details</h1>
<a href="../ContactsApp/"><h2> Back </h2></a>
<table>
<tr><th>First Name</th><th>Last Name</th><th>Email</th>
        <tr><td>{{ contact.first_name }}</td><td>{{ contact.last_name }}</td> <td>{{ contact.email }}</td> </tr>
</table>

<table>
<tr><th>Country Code</th><th>Phone Number</th>
{% for number in contact.phonenumber_set.all %}
        <tr><td>{{ number.country_code }}</td><td>{{ number.phone_number }}</td> </tr>
{% endfor %}
</table>

<a href="./add_new_number?contact_id={{ contact.id }}"><h3 style="color: green"> add new number </h3></a>

templates/ContactsApp/contacts.html
<h1> Contacts</h1>
<table>
<tr><th>First Name</th><th>Last Name</th><th>Show Contact</th>
{% for contact in contact_list %}
        <tr><td>{{ contact.first_name }}</td><td>{{ contact.last_name }}</td> <td> <a href="./get_contact_details?contact_id={{ contact.id }}"> show contact details</a></td> </tr>
{% endfor %}
</table>

<a href="./create_new_contact"><h3 style="color: green"> Creat new contact</h3></a>

templates/ContactsApp/create_contact.html
<h1>Create New Contact</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

templates/ContactsApp/create_number.html
<h1>Add new Number</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

templates/ContactsApp/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
<h1>Error</h1>
</body>
</html>